name: kgtk-env
channels:
  - conda-forge
  - defaults
dependencies:
  - sqlite3==3.34.1
  - pip==22.3.1
  - pip:
    - attrs==21.2.0
    - beautifulsoup4==4.10.0
    - blis==0.4.1
    - catalogue==1.0.0
    - chardet==4.0.0
    - charset-normalizer==2.0.8
    - click==8.0.3
    - cloudpickle==2.0.0
    - cssselect==1.1.0
    - cycler==0.11.0
    - cymem==2.0.6
    - cython==0.29.24
    - cytoolz==0.11.2
    - dask==2021.11.2
    - dateparser==1.1.0
    - decorator==5.1.0
    - deprecated==1.2.13
    - dill==0.3.4
    - distributed==2021.11.2
    - distro==1.6.0
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz#en_core_web_sm
    - en-core-web-sm-mirror==2.2.5
    - et-xmlfile==1.1.0
    - etk==2.2.8
    - faiss-cpu==1.7.3
    - fancycompleter==0.9.1
    - filelock==3.4.0
    - flask==2.0.1
    - fonttools==4.28.3
    - fsspec==2021.11.1
    - ftfy==6.0.3
    - h5py==3.6.0
    - heapdict==1.0.1
    - html5lib==1.1
    - huggingface-hub==0.2.1
    - idna==3.3
    - iso-639==0.4.5
    - isodate==0.6.0
    - itsdangerous==2.0.1
    - jdcal==1.4.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonpath-ng==1.5.3
    - kgtk==1.5.2
    - kiwisolver==1.3.2
    - langdetect==1.0.9
    - langid==1.1.6
    - lml==0.1.0
    - locket==0.2.1
    - loguru==0.5.3
    - lxml==4.6.4
    - lz4==3.1.10
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - mgzip==0.2.1
    - msgpack==1.0.3
    - msgpack-numpy==0.4.3.2
    - msgpack-python==0.5.6
    - multiprocess==0.70.12.2
    - murmurhash==1.0.6
    - mypy==0.910
    - mypy-extensions==0.4.3
    - nltk==3.6.5
    - numpy==1.21.4
    - odictliteral==1.0.0
    - openpyxl==3.0.9
    - owlrl==6.0.2
    - packaging==21.3
    - pandas==1.3.0
    - parsley==1.3
    - partd==1.2.0
    - pathlib==1.0.1
    - pdbpp==0.10.3
    - peewee==3.15.4
    - pillow==8.4.0
    - plac==1.1.3
    - ply==3.11
    - preshed==3.0.6
    - prettytable==2.4.0
    - psutil==5.8.0
    - pycountry==20.7.3
    - pyexcel==0.6.7
    - pyexcel-io==0.6.5
    - pyexcel-xls==0.7.0
    - pyexcel-xlsx==0.6.0
    - pygments==2.11.2
    - pygtrie==2.4.2
    - pyparsing==3.0.6
    - pyrallel-lib==0.0.9
    - pyrepl==0.9.0
    - pyshacl==0.19.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - rdflib==6.1.1
    - rdflib-jsonld==0.6.2
    - redis==4.0.2
    - regex==2021.11.10
    - requests==2.26.0
    - rfc3986==1.5.0
    - rltk==2.0.0a20
    - sacremoses==0.0.46
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - sentence-transformers==2.1.0
    - sentencepiece==0.1.96
    - setuptools-scm==6.3.2
    - sh==1.14.2
    - shortuuid==1.0.8
    - simplejson==3.17.6
    - six==1.16.0
    - sklearn==0.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - spacy==2.2.4
    - sparqlwrapper==1.8.5
    - srsly==1.0.5
    - tabula-py==2.3.0
    - tblib==1.7.0
    - termcolor==1.1.0
    - texttable==1.6.4
    - thinc==7.4.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==1.2.2
    - toolz==0.11.2
    - torch==1.10.0
    - torchbiggraph==1.0.0
    - torchvision==0.11.1
    - tornado==6.1
    - tqdm==4.62.3
    - transformers==4.12.5
    - typing==3.7.4.3
    - typing-extensions==4.0.1
    - tzdata==2021.5
    - tzlocal==4.1
    - ujson==4.3.0
    - unidecode==1.3.6
    - urllib3==1.26.7
    - usc-isi-i2-mgzip==0.2.1.3
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - wmctrl==0.4
    - wrapt==1.13.3
    - xlrd==2.0.1
    - xlwt==1.3.0
    - zict==2.0.0
